spring.application.name=SpartaTodo

# H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:sparta_todo
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (access at http://localhost:8091/h2-console)
spring.h2.console.enabled=true

server.port=8091

# Hibernate settings
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect